### PR TITLE
Closes #9 - Design database checks for app startup

### LINKED ISSUE #9: Design database checks for app startup
Some way to check that the database tables match what we expect when the app starts, and crash the app if it doesn't

Probably put it in [server.go](https://github.com/bobheadxi/calories/blob/dev/server/server.go) and call it from `main`

### PR DESCRIPTION
**Pull request by bwdmonkey**
### Related Issues
Closes #9 - Design database checks for app startup

### Description
- Did it
- Post-edit: Added a function called `CheckDB` that checks for the field names and data types

### Todos
 - Do something with the fail case.

### CODE REVIEW

**Comment by bobheadxi** [comment]
20 commits u cant be serious please learn to use `git amend` + `git push ... --force`

also better description please

File: main.go [hunk 1]
```diff
@@ -19,6 +19,12 @@ func main() {
 	// Set up Postgres connection
 	server := server.New(config)
 
+	// Start DB Schema check
+	if (!server.CheckDB()) {
+		// TODO: Do something when it fails
+		log.Fatal("RIP")
```
Comment (bobheadxi) [inline main.go]: `log,Fatal` is fine for now but please add a more descriptive error, ie "Database formatted incorrectly"

File: server/server.go [hunk 2]
```diff
@@ -2,6 +2,7 @@ package server
 
 import (
 	"database/sql"
+	_ "github.com/lib/pq"
```
Comment (bobheadxi) [inline server/server.go]: I don't think this should be here - global `_` imports should only exist in `main`. It's [already imported anyway](https://github.com/bobheadxi/calories/blob/dev/main.go#L10) - please switch to Visual Studio Code and use a real Go linter, which would probably tell you this

File: main.go (hunk 1 above)
Comment (bobheadxi) [inline main.go]: `log.Fatal` is fine for now but please add a more descriptive error, ie "Database formatted incorrectly"

File: server/server.go [hunk 3]
```diff
@@ -112,3 +114,69 @@ func (s *Server) SumCalories(id string) (int, error) {
...
+	sqlStatement := `
+	SELECT column_name, data_type
+	FROM information_schema.columns
+	WHERE table_name = 'users'`
+	rows, err := s.db.Query(sqlStatement)
+	if err != nil {
+		log.Print("CheckDB on Users failed: " + err.Error())
+		return false
+	}
+	idx := 0
```
Comment (bobheadxi) [inline server/server.go]: Please put `idx` closer to where it is used

File: server/server.go [hunk 4]
```diff
@@ -112,3 +114,69 @@ func (s *Server) SumCalories(id string) (int, error) {
...
+	sqlStatement = `
+	SELECT column_name, data_type
+	FROM information_schema.columns
+	WHERE table_name = 'entries'`
+	rows, err = s.db.Query(sqlStatement)
+	if err != nil {
+		log.Print("CheckDB on Entries failed: " + err.Error())
+		return false
+	}
+	idx = 0
```
Comment (bobheadxi) [inline server/server.go]: Same here - `idx` is specific to the loop, and should be right next to it

File: server/server.go [hunk 5]
```diff
@@ -112,3 +114,69 @@ func (s *Server) SumCalories(id string) (int, error) {
...
+	// col & typ reused
+	EntriesSchema := [...]string{"fuser_id", "time", "item", "calories"}
+	EntriesSchemaType := [...]string{"bigint", "bigint", "text", "bigint"}
```
Comment (bobheadxi) [inline server/server.go]: This can just be `[]string{ // your strings // }`

File: server/server.go [hunk 6]
```diff
@@ -112,3 +114,69 @@ func (s *Server) SumCalories(id string) (int, error) {
...
+	SELECT column_name, data_type
+	FROM information_schema.columns
+	WHERE table_name = 'entries'`
+	rows, err = s.db.Query(sqlStatement)
+	if err != nil {
+		log.Print("CheckDB on Entries failed: " + err.Error())
+		return false
+	}
+	idx = 0
+	// col & typ reused
```
Comment (bobheadxi) [inline server/server.go]: This comment isn't needed

File: server/server.go [hunk 7]
```diff
@@ -112,3 +114,69 @@ func (s *Server) SumCalories(id string) (int, error) {
 	}
 	return sum, nil
 }
+
+// CheckDB : return a boolean check on the database structure
+func (s *Server) CheckDB() (bool) {
```
Comment (bobheadxi) [inline server/server.go]: I don't think `bool` needs top be bracketed

**Review by bobheadxi — CHANGES_REQUESTED** [review]
nice nice, just some small things to fix. also still waiting on a better description

File: server/server.go (hunk 7 above)
Comment (bobheadxi) [reply server/server.go]: Also, just a thought but this function might be better named `CheckDatabaseIntegrity`

File: server/server.go [hunk 8]
```diff
@@ -112,3 +113,73 @@ func (s *Server) SumCalories(id string) (int, error) {
 	}
 	return sum, nil
 }
+
+// CheckDB : return a boolean check on the database structure
+func (s *Server) CheckDB() bool {
```
Comment (bobheadxi) [inline server/server.go]: This function might be better named `checkDatabaseIntegrity`, aka make it private, and instead of calling it in `main.go` call it it `Server.New()`.

That way we can avoid exposing this one-time function, which is only relevant to `server` startup

File: server/server.go [hunk 9]
```diff
@@ -112,3 +113,73 @@ func (s *Server) SumCalories(id string) (int, error) {
...
+	var col string
+	var typ string
+
+	UsersSchema := []string{"user_id", "max_cal", "timezone", "name"}
+	UsersSchemaType := []string{"bigint", "bigint", "integer", "text"}
+
+	defer rows.Close()
+
+	idx := 0
+	for rows.Next() {
```
Comment (bobheadxi) [inline server/server.go]: Sorry wasn't too clear - `defer` should be closest, since it is immediately relevant, so something like:
```go
idx := 0
defer rows.Close()
for rows.Next() { ... }
```

same for the other one

**Review by bobheadxi — CHANGES_REQUESTED** [review]

File: server/server.go (hunk 8 above)
Comment (bwdmonkey) [reply server/server.go]: Oh yea I was gonna ask you about that. I should just create a new var called svr or something and check return it or nil if wrong. Right?

Comment (bobheadxi) [reply server/server.go]: don't return nil - just `log.Fatal` it

**Review by bobheadxi — APPROVED** [review]
clean 😄
